# This is a basic workflow to help you get started with Actions

name: Verify DDF JSON

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    paths:
      - 'devices/*/*\.json'
      - 'generic/*/*\.json'
  pull_request:
    branches: [main]
    paths:
      - 'devices/*/*\.json'
      - 'generic/*/*\.json'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "validate"
  validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Validate DDF files
      - uses: deconz-community/ddf-validator-action@v1
        with:
          directory: devices
          generic: generic
          search: '**/*.json'
